apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # single key value properties
  log_level: "INFO"
  database_url: "jdbc:mysql://db-service:3306/prod"
  shard_enable: "true"

  # entire configuration file block
  app.properties: |
    server.port=8080
    cache.enabled=true
    max.connections=20
