apiVersion: v1
kind: Pod
metadata:
  name: backend-app
  namespace: default
spec:
  containers:
    - name: application-container
      image: nginx:alpine

      # Method A: Injecting individual fields as Environment Variables
      env:
        - name: APP_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: log_level
              name: app-config
      # Method B: mounting app.properties block as physical file
      volumeMounts:
        - mountPath: /etc/config
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: app-config